{
  parserClass="com.github.mrcheeze446.jetbrainsdcclasssupport.language.parser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="DC"
  psiImplClassSuffix="Impl"
  psiPackage="com.github.mrcheeze446.jetbrainsdcclasssupport.language.psi"
  psiImplPackage="com.github.mrcheeze446.jetbrainsdcclasssupport.language.psi"

  elementTypeHolderClass="com.github.mrcheeze446.jetbrainsdcclasssupport.language.DCClassTypes"
  elementTypeClass="com.github.mrcheeze446.jetbrainsdcclasssupport.language.psi.DCClassElementType"
  tokenTypeClass="com.github.mrcheeze446.jetbrainsdcclasssupport.language.psi.DCClassTokenType"
}

dcFile ::= item_*

private item_ ::= (property|COMMENT|CRLF)

property ::= (KEY? SEPARATOR VALUE?) | KEY