{
    parserClass="com.github.mrcheeze446.jetbrainsdcclasssupport.language.parser.DCClassParser"

    extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

    tokens=[
        SEMI = ";"
        EQ = "="
        LP="("
        RP=")"
        LB="["
        RB="]"
        LCB="{"
        RCB="}"
        MOD = "%"
        MULTIPLY = "*"
        PLUS = "+"
        MINUS = "-"
        DIVIDE = "/"

        letter = 'regexp:[aA-zZ]'
        decDigit = 'regexp:\d'
        octDigit = "regexp:[0-7]"
        hexDigit_1 = "regexp:\d"
        hexDigit_2 = "[aA-fF]"
        binDigit_0 = "0"
        binDigit_1 = "1"


        string="regexp:('([^\\]|\\.)*'|\"([^\"\\]|\\.)*\")"
        nonSingleQoute='"'
        SingleQuote="'"
        escapeCharacter="\\"

        decimal = 'regexp:\d+(\.\d*)?'
    ]
}